CC	:=/usr/bin/gcc
# Note : Assembly code used with C preprocessor 
AS	:=/usr/bin/as
LD	:=/usr/bin/ld
ARCH	:=x86
DEBUG	:=n
BOOTSTR	:=multiboot

# Build config flags

# no driver for logging kernel message,
# so delegate this to kernel (for now)
CONFIG_LOG_INPLACE :=
